Controllers/BookController.cs
using LibrarySite.Models;
using LibrarySite.MVC6.DataContext;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using System.Reflection.Metadata;

namespace LibrarySite.Controllers
{
    public class BookController : Controller
    {
        /// <summary>
        /// 도서 리스트
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int page, string keyword, string searchKind)
        {
            using (var db = new LibrarySiteDbContext())
            {
                //페이지
                int pageNum = 1;

                // maxListCount : 한 페이지에 불러올 컨텐츠의 수
                int maxListCount = 3;

                int totalCount = 0;

                //검색
                string keywordSearch = keyword ?? string.Empty;

                if (page > 0)
                {
                    pageNum = page;
                }

                ViewBag.Page = pageNum;

                int skip_count = (pageNum - 1) * maxListCount;


                var list = new List<Book>();

                if (string.IsNullOrWhiteSpace(keywordSearch))
                {
                    list = db.Books.OrderByDescending (x => x.BookNo)
                            .Skip(skip_count)
                            .Take(maxListCount).ToList();
                    totalCount = db.Books.Count();
                }
                else
                {
                    switch(searchKind)
                    {
                        case "BookTitle":
                            list = db.Books.Where(x => x.BookTitle.Contains(keywordSearch)).ToList();
                            totalCount = db.Books.Where(x => x.BookTitle.Contains(keywordSearch)).Count();
                            break;

                        case "BookWriter":
                            list = db.Books.Where(x => x.BookWriter.Contains(keywordSearch)).ToList();
                            totalCount = db.Books.Where(x => x.BookWriter.Contains(keywordSearch)).Count();
                            break;
                        case "BookPublisher":
                            list = db.Books.Where(x => x.BookPublisher.Contains(keywordSearch)).ToList();
                            totalCount = db.Books.Where(x => x.BookPublisher.Contains(keywordSearch)).Count();
                            break;
                        case "BookPublish_date":
                            list = db.Books.Where(x => x.BookPublish_date.Contains(keywordSearch)).ToList();
                            totalCount = db.Books.Where(x => x.BookPublish_date.Contains(keywordSearch)).Count();
                            break;
                        case "BookLocation":
                            list = db.Books.Where(x => x.BookLocation.Contains(keywordSearch)).ToList();
                            totalCount = db.Books.Where(x => x.BookLocation.Contains(keywordSearch)).Count();
                            break;
                    }

                    list = list.OrderByDescending (x => x.BookNo)
                            .Skip(skip_count)
                            .Take(maxListCount).ToList();
                    
                }

                ViewBag.Page = pageNum;
                ViewBag.TotalCount = totalCount;
                ViewBag.MaxListCount = maxListCount;
                ViewBag.SearchKind = searchKind;
                ViewBag.Keyword = keyword;

                return View(list);

            }

        }
        public IActionResult Detail(int bookNo)
        {
            using (var db = new LibrarySiteDbContext())
            {
                var book = db.Books.FirstOrDefault(n => n.BookNo.Equals(bookNo));
                return View(book);
            }
        }

        /// <summary>
        /// 도서 추가
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Add(Book model)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }

            model.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());

            if (ModelState.IsValid)
            {
                using (var db = new LibrarySiteDbContext())
                {
                    db.Books.Add(model);

                    if (db.SaveChanges() > 0)
                    {
                        return Redirect("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "도서을 저장할 수 없습니다.");
            }
            return View(model);
        }

        /// <summary>
        /// 도서 수정
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        /// <summary>
        /// 게시물 삭제
        /// </summary>
        /// <returns></returns>
        public IActionResult Delete(int bookNo)
        {
            using (var db = new LibrarySiteDbContext())
            {
                Book book = db.Books.Find(bookNo);
                db.Books.Remove(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

Controllers/NoteController.cs
using LibrarySite.Models;
using LibrarySite.MVC6.DataContext;
using Microsoft.AspNetCore.Mvc;
using PagedList;

namespace LibrarySite.Controllers
{
    public class NoteController : Controller
    {
        /// <summary>
        /// 게시물 리스트
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int page, string keyword, string searchKind)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            using (var db = new LibrarySiteDbContext())
            {
                //페이지
                int pageNum = 1;

                // maxListCount : 한 페이지에 불러올 컨텐츠의 수
                int maxListCount = 3;

                int totalCount = 0;

                //검색
                string keywordSearch = keyword ?? string.Empty;

                if (page > 0)
                {
                    pageNum = page;
                }

                ViewBag.Page = pageNum;

                int skip_count = (pageNum - 1) * maxListCount;


                var list = new List<Note>();

                if (string.IsNullOrWhiteSpace(keywordSearch))
                {
                    list = db.Notes.OrderByDescending (x => x.NoteNo)
                            .Skip(skip_count)
                            .Take(maxListCount).ToList();
                    totalCount = db.Notes.Count();
                }
                else
                {
                    switch(searchKind)
                    {
                        case "NoteTitle":
                            list = db.Notes.Where(x => x.NoteTitle.Contains(keywordSearch)).ToList();
                            totalCount = db.Notes.Where(x => x.NoteTitle.Contains(keywordSearch)).Count();
                            break;
                        case "UserNo":
                            list = db.Notes.Where(x => Convert.ToString(x.UserNo).Contains(keywordSearch)).ToList();
                            totalCount = db.Notes.Where(x => Convert.ToString(x.UserNo).Contains(keywordSearch)).Count();
                            break;
                    }

                    list = list.OrderByDescending (x => x.NoteNo)
                            .Skip(skip_count)
                            .Take(maxListCount).ToList();
                    
                }

                ViewBag.Page = pageNum;
                ViewBag.TotalCount = totalCount;
                ViewBag.MaxListCount = maxListCount;
                ViewBag.SearchKind = searchKind;
                ViewBag.Keyword = keyword;

                return View(list);

            }

        }
        public IActionResult Detail(int noteNo)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }

            using (var db = new LibrarySiteDbContext())
            {
                var note = db.Notes.FirstOrDefault(n => n.NoteNo.Equals(noteNo));
                return View(note);
            }
        }

        /// <summary>
        /// 게시물 추가
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Add(Note model)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }

            model.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());

            if (ModelState.IsValid)
            {
                using (var db = new LibrarySiteDbContext())
                {
                    db.Notes.Add(model);

                    if (db.SaveChanges() > 0)
                    {
                        return Redirect("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "게시물을 저장할 수 없습니다.");
            }
            return View(model);
        }

        /// <summary>
        /// 게시물 수정
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        /// <summary>
        /// 게시물 삭제
        /// </summary>
        /// <returns></returns>
        public IActionResult Delete(int noteNo)
        {
            using (var db = new LibrarySiteDbContext())
            {
                Note note = db.Notes.Find(noteNo);
                db.Notes.Remove(note);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibrarySite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/trumbowyg/dist/ui/trumbowyg.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibrarySite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">00도서관</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav navbar-nav">
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index" asp-route-page="1">자료 검색</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index" asp-route-page="1">문의 게시판</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (Context.Session.GetString("USER_LOGIN_KEY") == null)
                        {
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">회원가입</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">로그인</a></li>
                        }
                        else
                        {
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">로그아웃</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibrarySite - 김혜란
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="~/lib/trumbowyg/dist/plugins/upload/trumbowyg.upload.js"></script>
    <script src="~/lib/trumbowyg/dist/langs/ko.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>